### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by wong2** [joway/sheetsql#4]
We need to set proxy to access Google APIs in China

**Comment by joway** [comment]
You could set the following environment variables:

- `HTTP_PROXY` / `http_proxy`
- `HTTPS_PROXY` / `https_proxy`

https://github.com/joway/sheetsql/blob/master/README.md#using-a-proxy

**Comment by wong2** [comment]
Yeah I know but that is a global setting which means all http requests send with _request_ in my service will go through the proxy, which is not acceptable

**Comment by wong2** [comment]
Here is a related issue: https://github.com/googleapis/google-api-nodejs-client/issues/1943

**Comment by joway** [comment]
Hi, @wong2 , there are some conflicts when using `request` with `googleapis`. But there is also a workaround:

use the following environment variables
- HTTPS_PROXY=your_proxy_address
- NO_PROXY=*

`NO_PROXY` is used to control the proxy behavior in `request` lib, which could let `request` ignore all proxy environment variables but `googleapis` will not be impacted.

reference:
- https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables
https://github.com/googleapis/gaxios/blob/d21e08d2aada980d39bc5ca7093d54452be2d646/src/gaxios.ts#L53

**Comment by shirshak55** [comment]
@joway He got request package so you mentioned workaround? What about other case or package that uses HTTP_PROXY option?

**Comment by joway** [comment]
@shirshak55 sheetsql use `request` as the http package
