### ISSUE TITLE
Data inserted into wrong columns

### ISSUE THREAD

**Issue by ivankahl** [joway/sheetsql#9]
Hi, we have a sheet that we are using _sheetsql_ to save records into.  Sometimes the records seem to save offset to the right so all the data is stored in the wrong columns. See below for an example:
![image](https://user-images.githubusercontent.com/5931577/89932719-5e6bd700-dc0e-11ea-8969-37ccebec0ef1.png)

This only happens intermittently. I suspect it happens when we save a record after removing another record. Do you have any idea what might be causing this issue?

**Comment by joway** [comment]
@ivankahl  Hi, did you edit the sheets frequently? I cannot reproduce you problem when I write a simple example. https://github.com/joway/sheetsql/blob/master/example.ts

**Comment by rehangit** [comment]
@joway You can consider using drive api to read modified time to know if the sheet has been updated since last time. If the sheet has been updated it should be read again. For optimization this (update before save) can be done only before writing after a threshold duration has gone past (say 5 minutes).

**Comment by joway** [comment]
@rehangit thanks for your advice, it's an efficient solution! I will fix it when I have free time. But it's also welcome to submit a pr if you have the interest to fix it.

**Comment by ivankahl** [comment]
I am struggling to reproduce the issue but it appears to happen when making rapid updates to the sheet. A solution like @rehangit mentioned should work nicely.

**Comment by thucnc** [comment]
My 2 cents, Force the range `{SheetId}!A:A`  may solve this problem when appending new row always starts at column A.

**Comment by remorses** [comment]
I found that this happens when you add data in cells that are outside the schema

To fix it you can use the following code, it forces the insert to create a row
```ts
    // @ts-ignore
    db.storage.table = 'Sheet1!A:A'
    await db.insert(records)
    // @ts-ignore
    db.storage.table = 'Sheet1'
```
